version: '3.8'

services:
  coolify-hello-world:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coolify-hello-world-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - TZ=UTC
      - IMAGE_NAME=coolify-hello-world:latest
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/system || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coolify-hello-world.rule=Host(`hello-world.local`)"
      - "traefik.http.routers.coolify-hello-world.entrypoints=web,websecure"
      - "traefik.http.routers.coolify-hello-world.tls=true"
      - "traefik.http.services.coolify-hello-world.loadbalancer.server.port=3000"
      - "coolify.managed=true"
    networks:
      - coolify-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp
      - /app/.next/cache

networks:
  coolify-network:
    external: true
    name: coolify
